#!/usr/bin/env Rscript
# ==============================================================================
# launch_exploreDEG.R — Interactive SummarizedExperiment Viewer
#
# Launches an iSEE interactive browser for inspecting DEA results stored
# in a SummarizedExperiment .rds file generated by the pipeline.
#
# Usage:
#   Rscript launch_exploreDEG.R <target_directory>
#   Rscript launch_exploreDEG.R <path_to_SummarizedExperiment.rds>
#
# If a directory is given, looks for SummarizedExperiment.rds within it.
# If a .rds file is given directly, loads that file.
#
# The iSEE app provides interactive exploration of:
#   - PCA / reduced-dimension plots
#   - Heatmaps of assay data (raw + normalized)
#   - Volcano plots of differential expression contrasts
#   - Row/column metadata tables
#   - Feature-level abundance plots
# ==============================================================================

suppressPackageStartupMessages({
  library(SummarizedExperiment)
  library(iSEE)
})

# ---- Parse arguments ---------------------------------------------------------

args <- commandArgs(trailingOnly = TRUE)

if (length(args) < 1) {
  cat("Usage: Rscript launch_exploreDEG.R <target_directory_or_rds_file>\n\n")
  cat("Examples:\n")
  cat("  Rscript launch_exploreDEG.R C:/Data/MyExperiment\n")
  cat("  Rscript launch_exploreDEG.R C:/Data/MyExperiment/SummarizedExperiment.rds\n")
  quit(status = 1)
}

input_path <- normalizePath(args[1], mustWork = TRUE)

# Determine .rds path
if (dir.exists(input_path)) {
  rds_path <- file.path(input_path, "SummarizedExperiment.rds")
  if (!file.exists(rds_path)) {
    # Also check in DEA output subdirectories
    candidates <- list.files(input_path,
      pattern = "SummarizedExperiment\\.rds$",
      full.names = TRUE, recursive = TRUE
    )
    if (length(candidates) > 0) {
      rds_path <- candidates[1]
    } else {
      stop(
        "[ERROR] SummarizedExperiment.rds not found in: ", input_path, "\n",
        "  Run the pipeline first to generate this file.",
        call. = FALSE
      )
    }
  }
} else if (grepl("\\.rds$", input_path, ignore.case = TRUE)) {
  rds_path <- input_path
} else {
  stop("[ERROR] Input must be a directory or .rds file: ", input_path, call. = FALSE)
}

message("[exploreDEG] Loading: ", rds_path)


# ---- Load SummarizedExperiment -----------------------------------------------

se <- readRDS(rds_path)

if (!is(se, "SummarizedExperiment")) {
  stop(
    "[ERROR] The loaded object is not a SummarizedExperiment.\n",
    "  Class: ", class(se)[1],
    call. = FALSE
  )
}

message("[exploreDEG] Loaded SummarizedExperiment:")
message("  Dimensions: ", nrow(se), " features x ", ncol(se), " samples")
message("  Assays: ", paste(names(assays(se)), collapse = ", "))
message("  rowData columns: ", ncol(rowData(se)))
message("  colData columns: ", ncol(colData(se)))
message("  Metadata keys: ", paste(names(metadata(se)), collapse = ", "))


# ---- Launch iSEE -------------------------------------------------------------

message("\n[exploreDEG] Launching iSEE in your default browser...")
message("  Press Ctrl+C to stop the app.\n")

app <- iSEE::iSEE(se)
shiny::runApp(app, launch.browser = TRUE)
